### PR TITLE
Updated the version dates

### PR DESCRIPTION
**Pull request by DandelionSprout**
Under typical circumstances, the `Version:` and `Last modified:` values should be changed with each edit if possible, or else laymen could plausibly begin to think that the list hadn't been updated in 6 months.

While pointing this out, I figured I could also change them myself in a PR as a start boost.

### CODE REVIEW

**Comment by peace2000** [comment]
@DandelionSprout 

Hi!

I got write access to the Finnish Easylist. I was wondering if there was some kind of clever and "official" way to combine version and last modified values together:

```
[Adblock Plus 2.0]
! Version: 202002111
! Title: Adblock List for Finland
! Description: Finnish adblock list
! Last modified: 11th of February 2020
```
As I don't see any point to have two separate rows for those values. For e.g. version row shows also the date of the list. I asked theel0ja about this and he said to ask you and referenced to this old pull req and said that you know more about these things. :D

**Comment by DandelionSprout** [comment]
You've come to the right guy, more or less.

Okay, so essentially the distinction between `Version` and `Last modified`, seems to have been the result of how Adblock Plus' own issue tracker only accepts numerical values for `Version` to this day.

Since the Finnish list is currently not listed on https://adblockplus.org/subscriptions, nor has any direct connections with the ABP community that I'm aware of, this means that the numerical-only requirement does actually *not* apply to you guys. This essentially means that the `Version` value can be replaced with just about whatever. For instance, I use the date, as well as a sub-version for if I edit a list multiple times in one day, e.g. `! Version: 11February2020v1`, and I no longer use `Last modified` at all.

So my current personal recommendation is:

```
[Adblock Plus 2.0]
! Version: 11February2020v1
! Title: Adblock List for Finland
! Description: Finnish adblock list
```

Should you ever aim for re-inclusion in https://adblockplus.org/subscriptions, we can think of a modified strategy when that day comes.

(Previously I used a `! Version: 11February2020-19:05CET` format, which was unpractical when editing lists manually since I had to keep an eye on the clock before committing changes.)

**Comment by peace2000** [comment]
Clear and thorough answer, thanks.

I personally have never been in the ABP issue tracker nor I'm willing to use it. Github is enough for me. It's too annoying to monitor issue reports through many places...

I recently asked ABP people to add the Finnish list to ABP's default lists for Finnish users. They took it into consideration, dunno how long it takes and what is their final answer. Does it bring any bureaucratic demands for list maintainers if they add it?

Yeah, that time thing sounds very unpractical. I have noticed that some lists even use checksums. My willingness to contribute would drastically drop if there are too much bureaucratic demands for list maintaining...

Your recommendation looks great. I thought something like that at some point but I couldn't find any good looking syntax. Your syntax is good.

**Comment by DandelionSprout** [comment]
I have some memory of asking the ABP team a year ago to start their verification process for adding my west-Nordic list natively to ABP. I never heard from the support person again after that...

I remember testing out the checksum system at one point for a couple months, but it was bizarrely difficult to implement when using web-based list edits, plus it doesn't actually seem to be used by any up-to-date adblockers nowadays. So I'd say that checksums are completely skippable and ignorable in every way nowadays.

**Comment by DandelionSprout** [comment]
I maintain an all-major-adblockers syntax guide at https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md, which also aims to explain things like `! Version:`, `! Checksum:` (from today on), and many other such metadatas, if you ever were to need it.

**Comment by peace2000** [comment]
> I have some memory of asking the ABP team a year ago to start their verification process for adding my west-Nordic list natively to ABP. I never heard from the support person again after that...

Oh crap. :D It took for Ubo just one day and Adblocker Ultimate wanted to add it immediately when I contacted them... they were even grateful for my activity as they had one very old and abandoned Finnish list.


> So I'd say that checksums are completely skippable and ignorable in every way nowadays.

Strongly agree!


> I maintain an all-major-adblockers syntax guide at https://github.com/DandelionSprout/adfilt/blob/master/Wiki/SyntaxMeaningsThatAreActuallyHumanReadable.md

Thanks, this was helpful link for me.

**Comment by peace2000** [comment]
I checked through these lists: https://adblockplus.org/subscriptions

Not all of them use those values so it doesnt's seem to be so important. There are variation. Still they are accepted there:

https://stanev.org/abp/adblock_bg.txt
https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt
https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt

**Comment by DandelionSprout** [comment]
Now that you mention it, I suppose it was wrong of me to say that a numerical version was mandated by ABP. However, for lists without such, they're simply assigned incremental numbers instead that are pretty difficult to understand the context of. Things like `! Version: ILikeCornFlakes` would've been shown as e.g. `Version: 27` in the ABP issue tracker.

**Comment by peace2000** [comment]
Yeah, it would be stupid to require 3rd-party list maintainers to use ABP issue tracker as they share their lists with many different adblocker apps.

I however understand that some kind version/change tracking is necessary.

But anyway, this thing seems to be clear now, thanks for your knowledge! :)

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/ca5668a706afd8396cfe3bf985e945a9e3ae4afd Syntax updated now.

**Pull request merged**
