### PR TITLE
Filesize optimising

### PR DESCRIPTION
**Pull request by DandelionSprout**
I used the "Search for equal rules for which only the domain differs" tool of https://abpvn.com/ruleChecker/redundantRuleChecker.html, and also removed superfluous quotation marks.

Later on in a few weeks' time, I'll look into how to reduce the length of unusually long-winded entries, e.g. `arvopaperi.fi#?#div#skyscraper-height-div > div > div > div > div > div > a:-abp-contains(Kaupallinen yhteistyö)`

### CODE REVIEW

**Comment by peace2000** [comment]
Hi! Interesting, so quotes aren't always necessary then. Good to know.

This rule:

`kotiliesi.fi##body.category * .placeholder` does look kinda strange, but it was there for aesthetic reasons so I added it back (though I changed it to `kotiliesi.fi##body.category .placeholder` as it's not necessary to have an asterisk. Related conversation: https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/285

> Later on in a few weeks' time, I'll look into how to reduce the length of unusually long-winded entries, e.g. `arvopaperi.fi#?#div#skyscraper-height-div > div > div > div > div > div > a:-abp-contains(Kaupallinen yhteistyö)`

Yeah that's a long rule and to be honest, I wouldn't craft anymore a rule like that - it's an old rule a made long time ago when I was just kinda starting to learn how to write rules.

**Comment by DandelionSprout** [comment]
Quotes in square brackets can be skipped if the text consist *solely* of a-z, A-Z, 0-9, _, and -, from what I've figured out.

**Comment by peace2000** [comment]
Though then I wonder why this rule `##svg[width=16]` is consired invalid and this rule valid: `##svg[width="16"]` at least by Ubo's element picker. You try those in this comment section.

**Comment by DandelionSprout** [comment]
Wait, my fault. Entries that start with 0-9 still require quotes. I was sleepy when I wrote my comment above.

**Pull request merged**
