### PR TITLE
New adblocking complaint by Aamulehti

### PR DESCRIPTION
**Pull request by peace2000**
https://github.com/finnish-easylist-addition/finnish-easylist-addition/issues/41 (inserted a code in order to keep that issue open)

I suggest we keep that issue open and see if that value changes soon again.

### CODE REVIEW

**Comment by theel0ja** [comment]
We could use `:has-text()` for uBO

**Comment by peace2000** [comment]
> 
> 
> We could use `:has-text()` for uBO

Yes but this pull request for ABP?

**Comment by peace2000** [comment]
I tried has-text but didn't succeed. I got a blank page...

What about this?: aamulehti.fi##+js(overlay-buster.js)

https://github.com/gorhill/uBlock/wiki/Resources-Library#overlay-busterjs-

**Comment by peace2000** [comment]
Or maybe not because that complaint quickly displays anyway.

**Comment by peace2000** [comment]
Or wait not working if if refresh the page using ctrl + f5

**Comment by theel0ja** [comment]
> #41 (inserted a code in order to keep that issue open)
> 
> I suggest we keep that issue open and see if that value changes soon again.

You don't have to set code, because there's no "Fixes" or "Closes" trigger word before that.

**Comment by theel0ja** [comment]
> This whitelist rule `aamulehti.fi#@#div.ALMACR-container` seems to kill the adblock detector.

Not working on Adblock Plus though.

**Pull request merged**
