### PR TITLE
data-systems.fi cookie notification

### PR DESCRIPTION
**Pull request by peace2000**
Very annoying cookie notification!

### CODE REVIEW

**Comment by theel0ja** [comment]
The popup seems to generated by that `pum` script

**Comment by theel0ja** [comment]
Also I would suggest reporting cookie consents to Fanboy's Cookie List.

https://github.com/ryanbr/fanboy-adblock/issues/new

**Comment by peace2000** [comment]
Ok yes it seems that Annoyance list blocks it but the cookie list. I reported an issue.

**Comment by theel0ja** [comment]
https://github.com/ryanbr/fanboy-adblock/issues/830

**Pull request closed without merging**
