### PR TITLE
Finland_adb.txt: add rule for tori.fi middle-page campaign

### PR DESCRIPTION
**Pull request by mirmire**
I think it qualifies to be blocked. To verify: check Asunnot in tori \<https://www.tori.fi/koko_suomi/asunnot >, somewhere in the middle of the page, you see car offers.

### CODE REVIEW

**Comment by peace2000** [comment]
Hi, thank you for your contribution but this is self-promotion of own products, which is not typically blocked.

**Comment by theel0ja** [comment]
The ad container (`###banner_panorama_bottom`) should be blocked, though.

**Comment by peace2000** [comment]
Yeah tha't true.

**Comment by peace2000** [comment]
https://github.com/finnish-easylist-addition/finnish-easylist-addition/commit/cb96e6c63bbf90532ad6a218ec4a78110033efa7

**Pull request closed without merging**
