### PR TITLE
is.fi ad

### PR DESCRIPTION
**Pull request by peace2000**
kuva

`https://www.is.fi/taloussanomat/art-2000006342721.html`

### CODE REVIEW

**Comment by peace2000** [comment]
Not sure about that. I'll monitor things in case of changes are made.

**Comment by theel0ja** [comment]
Wouldn't it be possible to block by the image URL or something?

**Comment by peace2000** [comment]
Blocking an image will still leave a container. But this rule will block the image and container:

##.bg-white.lg\:w-main-lane.mb-16

Do you consider it better? I'll update this request.

**Comment by peace2000** [comment]
I'm not sure about that react app thing but I assume this rule would be ok, as that same ad is being used on another page and it has the element name: https://www.is.fi/taloussanomat/art-2000006376749.html

kuva

The elemeent in the picture above can be hidden with this rule: `##.overflow-hidden.relative.aspect-ratio-container.jsx-3817070661` which is the same rule.

**Comment by theel0ja** [comment]
Could just blocking https://is.mediadelivery.fi/img/230/84e171282a3e47c1af70371bcca99c7a.jpg`be enough?

**Comment by peace2000** [comment]
The problem is that it would leave an empty container behind:

kuva

**Comment by peace2000** [comment]
Can't then know what to do with this.

**Comment by peace2000** [comment]
But I think that I'll add this rule because it seems the only viable option. Other rules provided by the picker leave an ugly empty box. I'll monitor things and make required changes if needed. This element has been in use since December so I think it's safe.

I'll add this rule separately as this has conflicts now.

**Pull request closed without merging**
